name: greenville ink
favicon: null
layout_spectrum: 0.74245
typography_spectrum: 0.59664
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Greenville Ink
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161414'
    - '#8d8c8c'
    - '#cac4ba'
    - '#476079'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
