name: greenville ink
favicon: null
layout_spectrum: 1
typography_spectrum: 0.317725169705227
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Kenneth Lloyd Tshirts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f8f3'
    - '#020305'
    - '#182023'
    - '#aca49a'
    - '#5f6867'
  brandStrength: 0.6744901386555284
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.3986330912448466
purpose: []
