name: greenville ink
favicon: null
layout_spectrum: 0.88567
typography_spectrum: 0.59664
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Greenville Ink
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FAF9F7'
    - '#241E20'
    - '#72879F'
    - '#BFB8B3'
    - '#CC945B'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
